tooling:
  npm:
    service: node
    description: Runs npm commands
    cmd: npm
  wp-config:
    service: appserver
    description: Creates wp-config.php with default values (run it before installing for the first time).
    cmd: wp config create
    options:
      dbname:
        describe: The database name
        passthrough: true
        default: wordpress
      dbuser:
        describe: The database username
        passthrough: true
        default: wordpress
      dbpass:
        describe: The database password
        passthrough: true
        default: wordpress
      dbhost:
        describe: The database host
        passthrough: true
        default: database
  wp-install:
    service: appserver
    description: Runs 5-minute install in seconds (sets user/pass to admin/admin)
    cmd: wp core install --url=http://$LANDO_APP_NAME.$LANDO_DOMAIN --skip-email
    level: app
    options:
      admin_user:
        describe: The default admin user
        passthrough: true
        default: admin
      admin_password:
        describe: The default admin password
        passthrough: true
        default: admin
      admin_email:
        describe: The default admin email
        passthrough: true
        default: admin@lndo.site
      url:
        describe: The local site url
        passthrough: true
        default: http://localhost:1337
      title:
        describe: The Wordpress site title
        passthrough: true
        interactive:
          type: input
          message: What is the Wordpress site title going to be?
